version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    expose:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=mimi'

  app:
    build: ./
    container_name: 'java-app'
    depends_on:
      - 'postgres'
    ports:
      - "8080:8080"